eureka:
  client:
    register-with-eureka: true       # Register this service with Eureka
    fetch-registry: true             # Fetch the list of services from Eureka
    service-url:
      defaultZone: http://localhost:8090/eureka/  # Eureka server URL
